M48
; DRILL file {KiCad (5.99.0-11441-g1a5e63bcab)} date Mon Jul 19 16:29:49 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-07-19T16:29:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-11441-g1a5e63bcab)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X94.0Y-127.0
X110.0Y-127.0
T0
M30
